
package QLKS.Views;
import QLKS.Dao.QLPhongDao;
import QLKS.Models.CustomPhong;
import QLKS.Models.Phong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
public class QLPhongPanel extends javax.swing.JPanel {
    ArrayList<Phong> lstPhong = new ArrayList<>();
    QLPhongDao qlPhongDao= new QLPhongDao();
    public QLPhongPanel() {
        initComponents();
        loadCbbLoaiPhong();
        loadCbbTinhTrang();
        loadData();
    }
    public void loadData(){
        lstPhong = qlPhongDao.selectAllPhong();
        tb_Phong.setModel(new CustomPhong(lstPhong));
    }
    public void loadCbbLoaiPhong(){
        cbb_loaiPhong.addItem("Thường đơn");
        cbb_loaiPhong.addItem("Thường đôi");
        cbb_loaiPhong.addItem("Vip đơn");
        cbb_loaiPhong.addItem("Vip đôi");
    }
    public void loadCbbTinhTrang(){
        cbb_TinhTrang.addItem("Còn trống");
        cbb_TinhTrang.addItem("Đang sử dụng");
        cbb_TinhTrang.addItem("Đang bảo trì");
    }
    public void xoaTrang(){
        txt_maPhong.setText("");
        txta_ghiChu.setText("");
        txt_giaPhong.setText("");
        cbb_TinhTrang.setSelectedIndex(0);
        txt_giaPhong.isFocusable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_maPhongTC = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_maPhong = new javax.swing.JTextField();
        cbb_loaiPhong = new javax.swing.JComboBox<>();
        txt_giaPhong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_ghiChu = new javax.swing.JTextArea();
        cbb_TinhTrang = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_Phong = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        jLabel2.setText("Mã phòng:");

        btn_Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/find.png"))); // NOI18N
        btn_Tim.setText("Tìm kiếm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(txt_maPhongTC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_Tim)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maPhongTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tim)))
        );

        jLabel9.setText("Mã phòng:");

        jLabel10.setText("Loại phòng:");

        jLabel12.setText("Giá phòng:");

        jLabel13.setText("Tình trạng:");

        jLabel14.setText("Ghi chú:");

        txta_ghiChu.setColumns(20);
        txta_ghiChu.setRows(5);
        jScrollPane3.setViewportView(txta_ghiChu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_maPhong)
                    .addComponent(cbb_loaiPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_giaPhong)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(cbb_TinhTrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbb_loaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_giaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbb_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/add.png"))); // NOI18N
        btn_them.setText("Thêm mới");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/edit.png"))); // NOI18N
        btn_sua.setText("Chỉnh sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/load.png"))); // NOI18N
        btnLoad.setText("Reload");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_them)
                .addGap(18, 18, 18)
                .addComponent(btn_sua)
                .addGap(18, 18, 18)
                .addComponent(btn_xoa)
                .addGap(18, 18, 18)
                .addComponent(btnLoad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_Phong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_PhongMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tb_Phong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 185, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(txt_maPhong.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã phòng cần xóa hoặc click vào 1 dòng để xóa");
                return;
            }
            int dem=0;
            Iterator<Phong> it = lstPhong.iterator();
            while (it.hasNext()) {
                Phong next = it.next();
                if(next.getMaPhong().trim().equals(txt_maPhong.getText().trim())){
                    dem++;
                }
            }
            if(dem>0){
                 lstPhong.removeAll(lstPhong);
                if(JOptionPane.showConfirmDialog(this, "Xác nhận", "Xóa sinh viên này", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                qlPhongDao.detelePhong(txt_maPhong.getText().trim());
                loadData();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Mã phòng cần xóa không tồn tại");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        xoaTrang();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tb_PhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_PhongMouseClicked
        // TODO add your handling code here:
        int selectedRow= tb_Phong.getSelectedRow();
        if(selectedRow >= 0){
            txt_maPhong.setText(tb_Phong.getValueAt(selectedRow, 0)+"");
            cbb_loaiPhong.setSelectedItem(tb_Phong.getValueAt(selectedRow, 1)+"");
            txt_giaPhong.setText(tb_Phong.getValueAt(selectedRow, 2)+"");
            cbb_TinhTrang.setSelectedItem(tb_Phong.getValueAt(selectedRow, 3)+"");
            txta_ghiChu.setText(tb_Phong.getValueAt(selectedRow, 4)+"");
        }
    }//GEN-LAST:event_tb_PhongMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        try {
            if(txt_maPhong.getText().trim().equals("")||txt_giaPhong.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Mã phòng, giá phòng không được để trống");
                return;
            }
            int dem=0;
            Iterator<Phong> it = lstPhong.iterator();
            while (it.hasNext()) {
                Phong next = it.next();
                if(next.getMaPhong().trim().equals(txt_maPhong.getText().trim())){
                    dem++;
                }
            }
            if(dem==0){
                lstPhong.removeAll(lstPhong);
                qlPhongDao.insertPhong(txt_maPhong.getText().trim(), cbb_loaiPhong.getSelectedItem().toString(),Double.parseDouble(txt_giaPhong.getText().trim()),cbb_TinhTrang.getSelectedItem().toString(),txta_ghiChu.getText().trim());
                loadData();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            }
            else{
                JOptionPane.showMessageDialog(null, "Mã phòng đã tồn tại");
                //loadData();
                return;
            }
            xoaTrang();
        }
        catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try {
            if(txt_maPhong.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng click 1 dòng để sửa");
                return;
            }
            int dem=0;
            Iterator<Phong> it = lstPhong.iterator();
            while (it.hasNext()) {
                Phong next = it.next();
                if(next.getMaPhong().trim().equals(txt_maPhong.getText().trim())){
                    dem++;
                }
            }
            if(dem!=0){
                lstPhong.removeAll(lstPhong);
                qlPhongDao.updatePhong(txt_maPhong.getText().trim(), cbb_loaiPhong.getSelectedItem().toString(),Double.parseDouble(txt_giaPhong.getText().trim()),cbb_TinhTrang.getSelectedItem().toString(),txta_ghiChu.getText().trim());
                loadData();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            }
            else{
                JOptionPane.showMessageDialog(null, "Không tồn tại mã phòng cần sửa");
                return;
            }
            xoaTrang();
        }
        catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<Phong> lstCanTim=new ArrayList<>();
            // TODO add your handling code here
            if(txt_maPhongTC.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã phòng cần tìm");
                return;
            }
            int dem=0;
            Iterator<Phong> it = lstPhong.iterator();
            while (it.hasNext()) {
                Phong next = it.next();
                if(next.getMaPhong().trim().equals(txt_maPhongTC.getText().trim())){
                    dem++;
                }
            }
            if(dem>0){
                    lstCanTim=qlPhongDao.findPhong(txt_maPhongTC.getText().trim());
                    tb_Phong.setModel(new CustomPhong(lstCanTim));
                    JOptionPane.showMessageDialog(null, "Có tìm thấy thông tin về phòng này"); 
            }
            else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy phòng có mã này");
            }
            xoaTrang();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        txt_maPhongTC.setText("");
    }//GEN-LAST:event_btn_TimActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        lstPhong.removeAll(lstPhong);
        loadData();
        xoaTrang();
    }//GEN-LAST:event_btnLoadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_TinhTrang;
    private javax.swing.JComboBox<String> cbb_loaiPhong;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable tb_Phong;
    private javax.swing.JTextField txt_giaPhong;
    private javax.swing.JTextField txt_maPhong;
    private javax.swing.JTextField txt_maPhongTC;
    private javax.swing.JTextArea txta_ghiChu;
    // End of variables declaration//GEN-END:variables
}
